config system console
set output standard
end
config system global
set timezone "Asia/Kolkata"
end
config system interface
edit "port2"
set mode static
set ip 10.10.1.1 255.255.255.0
set allowaccess ping
set alias "lab-clients"
set role lan
next
end
config firewall address
edit "lab-clients"
set subnet 10.10.1.0 255.255.255.0
next
edit "lab-server"
set subnet 172.20.20.10 255.255.255.255
next
end
config firewall policy
edit 1
set name "allow-web"
set srcintf "port2"
set dstintf "port1"
set action accept
set srcaddr "lab-clients"
set dstaddr "lab-server"
set schedule "always"
set service "HTTP" "PING"
set nat enable
set logtraffic all
next
edit 2
set name "deny-rest"
set srcintf "port2"
set dstintf "port1"
set action deny
set srcaddr "all"
set dstaddr "all"
set schedule "always"
set service "ALL"
set logtraffic all
next
end
config log syslogd setting
set status enable
set server "172.20.20.1"
set mode reliable
set port 6515
set format default
end
y
config log syslogd filter
set severity information
set forward-traffic enable
set local-traffic enable
set multicast-traffic disable
set sniffer-traffic disable
end
